# Generated by Django 5.1.4 on 2024-12-08 12:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=500, verbose_name='Ситуация')),
                ('feelings', models.TextField(verbose_name='Чувства')),
                ('reactions', models.CharField(blank=True, max_length=250, null=True, verbose_name='Рекации')),
                ('thoughts', models.TextField(blank=True, null=True, verbose_name='Мысли')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'дневник',
                'verbose_name_plural': 'дневники',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=250, verbose_name='План')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнение')),
            ],
            options={
                'verbose_name': 'план',
                'verbose_name_plural': 'планы',
            },
        ),
        migrations.CreateModel(
            name='YearList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Год')),
            ],
            options={
                'verbose_name': 'чек-лист на год',
                'verbose_name_plural': 'чек-листы на год',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Wishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Желание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yearlist', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'желание',
                'verbose_name_plural': 'желания',
            },
        ),
        migrations.CreateModel(
            name='Thanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thank', models.CharField(max_length=250, verbose_name='Благодароность')),
                ('object', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кому/чему')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yearlist', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'благодарность',
                'verbose_name_plural': 'благодарности',
            },
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Привычка')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новая привычка')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yearlist', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
        migrations.CreateModel(
            name='GoalsYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название цели')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yearlist', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'цель на год',
                'verbose_name_plural': 'цели на год',
            },
        ),
    ]
