# Generated by Django 5.1.4 on 2025-01-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_habits_is_new_remove_plans_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
